import {
  type Product,
  type InsertProduct,
  type CartItem,
  type InsertCartItem,
  type CartItemWithProduct,
} from "@shared/schema";
import { randomUUID } from "crypto";

// Storage interface
export interface IStorage {
  // Products
  getAllProducts(): Promise<Product[]>;
  getProductById(id: string): Promise<Product | undefined>;
  getProductBySlug(slug: string): Promise<Product | undefined>;
  getProductsByCategory(category: string): Promise<Product[]>;
  createProduct(product: InsertProduct): Promise<Product>;

  // Cart
  getCartItems(sessionId: string): Promise<CartItemWithProduct[]>;
  addToCart(item: InsertCartItem): Promise<CartItem>;
  updateCartItemQuantity(id: string, quantity: number): Promise<CartItem | undefined>;
  removeFromCart(id: string): Promise<boolean>;
}

export class MemStorage implements IStorage {
  private products: Map<string, Product>;
  private cartItems: Map<string, CartItem>;

  constructor() {
    this.products = new Map();
    this.cartItems = new Map();
    this.seedProducts();
  }

  private seedProducts() {
    const productsData: Omit<Product, 'id'>[] = [
      {
        name: "M18 FUEL Wiertarko-wkrętarka udarowa",
        slug: "m18-fuel-wiertarko-wkretarka",
        category: "wiertarki",
        description:
          "Profesjonalna wiertarko-wkrętarka udarowa M18 FUEL z silnikiem bezszczotkowym POWERSTATE™. Maksymalny moment obrotowy 158 Nm, kompaktowa konstrukcja idealna do pracy w ograniczonych przestrzeniach.",
        originalPrice: "899.00",
        exhibitionPrice: "549.00",
        image: "/attached_assets/generated_images/Milwaukee_cordless_drill_product_f5b6aa57.png",
        sku: "M18FPD3-0X",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Silnik bezszczotkowy POWERSTATE™",
          "Maksymalny moment obrotowy: 158 Nm",
          "Prędkość obrotowa: 0-550/0-2100 obr/min",
          "Uchwyt szybkozaciskowy 13mm",
          "Podświetlenie LED",
          "Kompaktowa długość: 175mm",
        ],
      },
      {
        name: "M18 FUEL Szlifierka kątowa 125mm",
        slug: "m18-fuel-szlifierka-katowa-125mm",
        category: "szlifierki",
        description:
          "Bezprzewodowa szlifierka kątowa M18 FUEL 125mm z silnikiem bezszczotkowym. System RAPIDSTOP™ zatrzymuje tarczę w mniej niż 3 sekundy dla bezpieczeństwa.",
        originalPrice: "749.00",
        exhibitionPrice: "459.00",
        image: "/attached_assets/generated_images/Milwaukee_angle_grinder_product_73120ad4.png",
        sku: "M18CAG125XPD-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Średnica tarczy: 125mm",
          "Prędkość obrotowa: 8500 obr/min",
          "System RAPIDSTOP™",
          "Silnik bezszczotkowy POWERSTATE™",
          "Blokada wrzeciona",
          "Osłona przeciwpyłowa",
        ],
      },
      {
        name: "M18 FUEL Klucz udarowy 1/2\"",
        slug: "m18-fuel-klucz-udarowy",
        category: "klucze",
        description:
          "Najwydajniejszy klucz udarowy akumulatorowy 1/2\". Moment zrywający do 1898 Nm, moment dokręcania 1356 Nm. Idealny do prac warsztatowych i napraw samochodowych.",
        originalPrice: "1299.00",
        exhibitionPrice: "799.00",
        image: "/attached_assets/generated_images/Milwaukee_impact_wrench_product_0a592840.png",
        sku: "M18FHIWF12-0X",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Moment zrywający: 1898 Nm",
          "Moment dokręcania: 1356 Nm",
          "4 tryby DRIVE CONTROL™ (130/400/1356/1898 Nm)",
          "Napęd kwadratowy 1/2\"",
          "Długość: 213mm",
          "Pierścień ochronny",
        ],
      },
      {
        name: "M18 FUEL Młot udarowo-obrotowy SDS-Plus",
        slug: "m18-fuel-mlot-udarowo-obrotowy",
        category: "mloty",
        description:
          "Bezprzewodowy młot udarowo-obrotowy M18 FUEL z systemem SDS-Plus. Energia uderzenia 2.5J, idealny do wiercenia w betonie do 26mm.",
        originalPrice: "1099.00",
        exhibitionPrice: "679.00",
        image: "/attached_assets/generated_images/Milwaukee_rotary_hammer_product_8706618f.png",
        sku: "M18FHX-0X",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Energia uderzenia: 2.5J",
          "Wiercenie w betonie: do 26mm",
          "3 tryby pracy: wiercenie, wiercenie z udarem, kucie",
          "System SDS-Plus",
          "Sprzęgło bezpieczeństwa",
          "Wibracje: 13.5 m/s²",
        ],
      },
      {
        name: "M18 FUEL Wiertarko-wkrętarka 13mm",
        slug: "m18-fuel-wiertarka-13mm",
        category: "wiertarki",
        description:
          "Kompaktowa wiertarko-wkrętarka M18 FUEL z uchwytem 13mm bez udaru. Moment obrotowy 158 Nm, idealna do precyzyjnych prac montażowych i instalacyjnych.",
        originalPrice: "699.00",
        exhibitionPrice: "429.00",
        image: "/attached_assets/generated_images/Milwaukee_cordless_drill_product_f5b6aa57.png",
        sku: "M18FDD3-0X",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Moment obrotowy: 158 Nm",
          "Prędkość obrotowa: 0-550/0-2100 obr/min",
          "Uchwyt metalowy 13mm",
          "Długość: 173mm",
          "Waga: 2.1kg z akumulatorem",
          "Podświetlenie LED",
        ],
      },
      {
        name: "M18 Szlifierka kątowa 230mm",
        slug: "m18-szlifierka-230mm",
        category: "szlifierki",
        description:
          "Mocna szlifierka kątowa 230mm do wymagających zastosowań. Idealna do cięcia i szlifowania dużych powierzchni.",
        originalPrice: "899.00",
        exhibitionPrice: "559.00",
        image: "/attached_assets/generated_images/Milwaukee_angle_grinder_product_73120ad4.png",
        sku: "M18CAG230XPD-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Średnica tarczy: 230mm",
          "Prędkość obrotowa: 6600 obr/min",
          "Blokada wrzeciona",
          "Osłona metalowa",
          "Uchwyt dodatkowy",
          "System AVS - redukcja wibracji",
        ],
      },
      {
        name: "M18 FUEL Klucz udarowy kompaktowy 1/4\"",
        slug: "m18-fuel-klucz-udarowy-kompaktowy",
        category: "klucze",
        description:
          "Kompaktowy klucz udarowy 1/4\" hex idealny do prac montażowych. Moment obrotowy do 220 Nm w niewielkiej obudowie.",
        originalPrice: "599.00",
        exhibitionPrice: "369.00",
        image: "/attached_assets/generated_images/Milwaukee_impact_wrench_product_0a592840.png",
        sku: "M18FID2-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Maksymalny moment: 220 Nm",
          "Napęd hex 1/4\"",
          "Prędkość uderzenia: do 3600 uderzeń/min",
          "Długość: tylko 137mm",
          "4 tryby pracy",
          "Podświetlenie LED",
        ],
      },
      {
        name: "M18 FUEL Pilarka tarczowa 184mm",
        slug: "m18-fuel-pilarka-tarczowa",
        category: "pily",
        description:
          "Bezprzewodowa pilarka tarczowa M18 FUEL z tarczą 184mm. Moc i precyzja cięcia porównywalna z pilarkami sieciowymi.",
        originalPrice: "899.00",
        exhibitionPrice: "559.00",
        image: "/attached_assets/generated_images/Cordless_circular_saw_tool_2d9dd3d9.png",
        sku: "M18CCS66-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Średnica tarczy: 184mm",
          "Prędkość obrotowa: 5800 obr/min",
          "Głębokość cięcia 90°: 66mm",
          "Głębokość cięcia 45°: 48mm",
          "Silnik bezszczotkowy POWERSTATE™",
          "Prowadnica laserowa",
        ],
      },
      {
        name: "M18 FUEL Multi-Tool",
        slug: "m18-fuel-multi-tool",
        category: "akcesoria",
        description:
          "Uniwersalne narzędzie oscylacyjne M18 FUEL. Szeroki zakres zastosowań - cięcie, szlifowanie, usuwanie fug.",
        originalPrice: "649.00",
        exhibitionPrice: "399.00",
        image: "/attached_assets/generated_images/Multi-tool_oscillating_tool_be255d0e.png",
        sku: "M18FMT-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Częstotliwość oscylacji: 10000-20000 obr/min",
          "Kąt oscylacji: 4.2°",
          "Regulacja prędkości",
          "System szybkiej wymiany akcesoriów",
          "Podświetlenie LED",
          "Silnik bezszczotkowy",
        ],
      },
      {
        name: "M18 FUEL Wyrzynarka",
        slug: "m18-fuel-wyrzynarka",
        category: "pily",
        description:
          "Precyzyjna wyrzynarka M18 FUEL do krzywoliniowego cięcia drewna, metalu i tworzyw sztucznych.",
        originalPrice: "699.00",
        exhibitionPrice: "439.00",
        image: "/attached_assets/generated_images/Cordless_jigsaw_power_tool_8528d658.png",
        sku: "M18FBJS-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Skok ostrza: 26mm",
          "Prędkość ruchu: 0-3500 skoków/min",
          "Głębokość cięcia w drewnie: 135mm",
          "Funkcja wahadła (4 pozycje)",
          "Podświetlenie LED",
          "Mocowanie ostrza bez narzędzi",
        ],
      },
      {
        name: "M18 Szlifierka taśmowa",
        slug: "m18-szlifierka-tasmowa",
        category: "szlifierki",
        description:
          "Bezprzewodowa szlifierka taśmowa M18 z taśmą 10x330mm. Idealna do szlifowania powierzchni drewnianych.",
        originalPrice: "849.00",
        exhibitionPrice: "529.00",
        image: "/attached_assets/generated_images/Belt_sander_power_tool_90c20a1d.png",
        sku: "M18FBS10-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Wymiar taśmy: 10x330mm",
          "Prędkość taśmy: 350 m/min",
          "Regulacja prędkości",
          "Worek na pył",
          "System szybkiej wymiany taśmy",
          "Silnik bezszczotkowy",
        ],
      },
      {
        name: "M18 FUEL Frezarka",
        slug: "m18-fuel-frezarka",
        category: "akcesoria",
        description:
          "Uniwersalna frezarka M18 FUEL do obróbki drewna. Moc i precyzja w kompaktowej bezprzewodowej obudowie.",
        originalPrice: "799.00",
        exhibitionPrice: "499.00",
        image: "/attached_assets/generated_images/Cordless_router_power_tool_333a6c73.png",
        sku: "M18FTR-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Prędkość obrotowa: 10000-31000 obr/min",
          "Chwyty: 6mm i 8mm",
          "Regulacja głębokości: 0-51mm",
          "Silnik bezszczotkowy POWERSTATE™",
          "Elektroniczna kontrola prędkości",
          "Mocna płyta bazowa",
        ],
      },
      {
        name: "Wózek narzędziowy 10-szufladowy",
        slug: "wozek-narzedzi-10-szuflad",
        category: "wozki",
        description:
          "Profesjonalny wózek narzędziowy z 10 szufladami o różnej wysokości. Wytrzymała stalowa konstrukcja z blokowaniem szuflad.",
        originalPrice: "3499.00",
        exhibitionPrice: "2199.00",
        image: "/attached_assets/generated_images/Rolling_tool_chest_storage_f9de8152.png",
        sku: "MWTC10-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "10 szuflad z pełnym wysuwem",
          "Nośność: 680 kg",
          "Wymiary: 1118 x 610 x 1016 mm",
          "Stalowa konstrukcja",
          "Blokada szuflad",
          "4 wzmocnione kółka z hamulcem",
          "Mata antypoślizgowa w szufladach",
          "Uchwyt na butelkę",
        ],
      },
      {
        name: "Wózek narzędziowy mobilny 6-szufladowy",
        slug: "wozek-mobilny-6-szuflad",
        category: "wozki",
        description:
          "Mobilny wózek narzędziowy z 6 szufladami idealny do warsztatu lub garażu. Kompaktowy i manewrowy.",
        originalPrice: "2299.00",
        exhibitionPrice: "1449.00",
        image: "/attached_assets/generated_images/Tool_trolley_cart_storage_4950d2c9.png",
        sku: "MWTC6-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "6 szuflad z łożyskami kulkowymi",
          "Nośność: 450 kg",
          "Wymiary: 711 x 457 x 965 mm",
          "Konstrukcja stalowa z powłoką proszkową",
          "Centralny zamek szuflad",
          "4 obrotowe kółka",
          "Blat roboczy",
          "Wytrzymały uchwyt",
        ],
      },
      {
        name: "Skrzynia narzędziowa przejezdna",
        slug: "skrzynia-przejezdna",
        category: "wozki",
        description:
          "Duża skrzynia narzędziowa na kółkach z wysuwanym uchwytem. Idealna do transportu narzędzi na budowę.",
        originalPrice: "1799.00",
        exhibitionPrice: "1099.00",
        image: "/attached_assets/generated_images/Rolling_tool_chest_storage_f9de8152.png",
        sku: "MWTB-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Pojemność: 170 litrów",
          "Wytrzymały tworzywo sztuczne",
          "Wysuwalny teleskopowy uchwyt",
          "2 duże koła terenowe",
          "Zamykana pokrywa",
          "Organizery wewnętrzne",
          "Uchwyt górny do przenoszenia",
          "Odporna na warunki atmosferyczne",
        ],
      },
      // Dodatkowe wózki narzędziowe
      {
        name: "Wózek warsztatowy 7-szufladowy Premium",
        slug: "wozek-warsztatowy-7-szuflad-premium",
        category: "wozki",
        description:
          "Premium wózek warsztatowy z 7 szufladami i blatem roboczym. Idealne rozwiązanie do profesjonalnego warsztatu.",
        originalPrice: "2899.00",
        exhibitionPrice: "1799.00",
        image: "",
        sku: "MWTC7P-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "7 szuflad na łożyskach kulkowych",
          "Blat roboczy ze stali nierdzewnej",
          "Nośność: 500 kg",
          "Panel boczny na narzędzia",
          "Uchwyty na papier i pojemniki",
          "Zabezpieczenie przed wywróceniem",
        ],
      },
      {
        name: "Wózek narzędziowy kompaktowy 5-szufladowy",
        slug: "wozek-kompaktowy-5-szuflad",
        category: "wozki",
        description:
          "Kompaktowy wózek narzędziowy doskonały do małych warsztatów i garaży domowych.",
        originalPrice: "1599.00",
        exhibitionPrice: "999.00",
        image: "",
        sku: "MWTC5C-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "5 szuflad różnej wysokości",
          "Wymiary: 660 x 330 x 860 mm",
          "Nośność: 200 kg",
          "Zintegrowany uchwyt",
          "4 kółka obrotowe",
          "Stalowa konstrukcja",
        ],
      },
      {
        name: "Stacja robocza mobilna 3-modułowa",
        slug: "stacja-robocza-mobilna-3-modulowa",
        category: "wozki",
        description:
          "Modułowa stacja robocza składająca się z 3 elementów. Maksymalna elastyczność organizacji narzędzi.",
        originalPrice: "4299.00",
        exhibitionPrice: "2699.00",
        image: "",
        sku: "MWMS3-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "3 moduły stackowalne",
          "Szafka górna + wózek środkowy + szafka dolna",
          "Łączna nośność: 900 kg",
          "System bloków do wszystkich modułów",
          "Blat roboczy składany",
          "Gniazdka elektryczne 230V",
        ],
      },
      {
        name: "Wózek serwisowy z organizerami",
        slug: "wozek-serwisowy-organizery",
        category: "wozki",
        description:
          "Specjalistyczny wózek serwisowy wyposażony w liczne organizery i uchwyty na narzędzia.",
        originalPrice: "1899.00",
        exhibitionPrice: "1199.00",
        image: "",
        sku: "MWTS-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "4 szuflady + blat organizacyjny",
          "Panele boczne na narzędzia",
          "Uchwyty na wkrętaki i klucze",
          "Pojemniki na drobne elementy",
          "Uchwyt na tablet",
          "Wymiary: 850 x 450 x 950 mm",
        ],
      },
      {
        name: "Szafa narzędziowa mobilna 12-szufladowa",
        slug: "szafa-narzędziowa-12-szuflad",
        category: "wozki",
        description:
          "Duża szafa narzędziowa na kółkach z 12 szufladami. Maksymalna pojemność dla profesjonalistów.",
        originalPrice: "5499.00",
        exhibitionPrice: "3499.00",
        image: "",
        sku: "MWTC12-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "12 szuflad pełnowymiarowych",
          "Nośność: 1000 kg",
          "Wymiary: 1220 x 610 x 1220 mm",
          "Centralny system blokowania",
          "Wzmocnione kółka z hamulcami",
          "Boczne panele magnetyczne",
        ],
      },
      {
        name: "Wózek niskoprofilowy pod auto",
        slug: "wozek-niskoprofilowy-auto",
        category: "wozki",
        description:
          "Specjalistyczny wózek niskoprofilowy idealny dla mechaników samochodowych.",
        originalPrice: "1299.00",
        exhibitionPrice: "799.00",
        image: "",
        sku: "MWTL-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Niska wysokość: 280 mm",
          "6 płaskich szuflad",
          "Idealne pod podnośnik",
          "Kółka z miękką bieżnią",
          "Nośność: 150 kg",
          "Powłoka odporna na olej",
        ],
      },
      {
        name: "Stacja pakująca mobilna",
        slug: "stacja-pakujaca-mobilna",
        category: "wozki",
        description:
          "Mobilna stacja pakująca z miejscem na papier, taśmy i materiały pakowe.",
        originalPrice: "1799.00",
        exhibitionPrice: "1099.00",
        image: "",
        sku: "MWPS-0",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: [
          "Uchwyt na rolki papieru",
          "Podajnik taśm klejących",
          "2 szuflady na akcesoria",
          "Blat roboczy 900x600 mm",
          "Kosz na odpady",
          "4 kółka skrętne",
        ],
      },
      // Dodatkowe wiertarki
      {
        name: "M12 FUEL Wiertarka kątowa",
        slug: "m12-fuel-wiertarka-katowa",
        category: "wiertarki",
        description: "Kompaktowa wiertarka kątowa M12 FUEL idealna do pracy w ograniczonych przestrzeniach.",
        originalPrice: "649.00",
        exhibitionPrice: "399.00",
        image: "",
        sku: "M12FAD-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Głowica kątowa", "Silnik bezszczotkowy", "Moment: 30 Nm", "Kompaktowa konstrukcja"],
      },
      {
        name: "M18 Wiertarka udarowa Heavy Duty",
        slug: "m18-wiertarka-udarowa-heavy-duty",
        category: "wiertarki",
        description: "Wytrzymała wiertarka udarowa do ciężkich zastosowań.",
        originalPrice: "999.00",
        exhibitionPrice: "629.00",
        image: "",
        sku: "M18PD-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Moment: 90 Nm", "Uchwyt 13mm", "Metal uchwyt", "Tryb udarowy"],
      },
      {
        name: "M18 FUEL Wiertarka diamentowa",
        slug: "m18-fuel-wiertarka-diamentowa",
        category: "wiertarki",
        description: "Wiertarka do wierceń diamentowych w betonie i kamieniu.",
        originalPrice: "1499.00",
        exhibitionPrice: "949.00",
        image: "",
        sku: "M18FDD-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Wiercenie diamentowe", "Koron max 162mm", "System chłodzenia wodą", "Elektronika REDLINK"],
      },
      {
        name: "M12 Wiertarka kompaktowa",
        slug: "m12-wiertarka-kompaktowa",
        category: "wiertarki",
        description: "Ultra kompaktowa wiertarka M12 do precyzyjnych prac.",
        originalPrice: "499.00",
        exhibitionPrice: "299.00",
        image: "",
        sku: "M12BD-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Długość: 169mm", "Waga: 0.6kg", "Moment: 20 Nm", "LED podświetlenie"],
      },
      // Dodatkowe szlifierki
      {
        name: "M18 Szlifierka oscylacyjna",
        slug: "m18-szlifierka-oscylacyjna",
        category: "szlifierki",
        description: "Szlifierka oscylacyjna do wykończeń i delikatnych prac.",
        originalPrice: "799.00",
        exhibitionPrice: "499.00",
        image: "",
        sku: "M18BOS-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Ruch oscylacyjny", "Regulacja prędkości", "Odpylanie", "Płyta 93x186mm"],
      },
      {
        name: "M18 Szlifierka prosta",
        slug: "m18-szlifierka-prosta",
        category: "szlifierki",
        description: "Szlifierka prosta do prac precyzyjnych i grawerowania.",
        originalPrice: "699.00",
        exhibitionPrice: "449.00",
        image: "",
        sku: "M18FDG-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Chwyt 6mm", "Prędkość: 28000 obr/min", "Ergonomiczny chwyt", "LED"],
      },
      {
        name: "M12 Szlifierka kątowa mini",
        slug: "m12-szlifierka-katowa-mini",
        category: "szlifierki",
        description: "Kompaktowa szlifierka kątowa 75mm idealna do szczegółów.",
        originalPrice: "549.00",
        exhibitionPrice: "339.00",
        image: "",
        sku: "M12CAG-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza: 75mm", "Prędkość: 20000 obr/min", "Kompaktowa", "Waga: 1.4kg"],
      },
      {
        name: "M18 FUEL Szlifierka kątowa 180mm",
        slug: "m18-fuel-szlifierka-katowa-180mm",
        category: "szlifierki",
        description: "Duża szlifierka kątowa do wymagających zastosowań przemysłowych.",
        originalPrice: "1099.00",
        exhibitionPrice: "699.00",
        image: "",
        sku: "M18CAG180-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza: 180mm", "Silnik bezszczotkowy", "System AVS", "Blokada wrzeciona"],
      },
      {
        name: "M18 Polerka rotacyjna",
        slug: "m18-polerka-rotacyjna",
        category: "szlifierki",
        description: "Profesjonalna polerka do lakieru samochodowego i kamienia.",
        originalPrice: "849.00",
        exhibitionPrice: "529.00",
        image: "",
        sku: "M18FAP-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Średnica: 180mm", "Prędkość: 0-2800 obr/min", "Regulacja elektroniczna", "Uchwyt boczny"],
      },
      {
        name: "M18 Szlifierka do betonu",
        slug: "m18-szlifierka-betonu",
        category: "szlifierki",
        description: "Specjalistyczna szlifierka do prac w betonie i kamieniu.",
        originalPrice: "1299.00",
        exhibitionPrice: "849.00",
        image: "",
        sku: "M18FCOS-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza diamentowa 125mm", "Odśysanie pyłu", "Głębokość cięcia: 45mm", "Prowadnica"],
      },
      // Dodatkowe klucze udarowe
      {
        name: "M18 FUEL Klucz udarowy 3/4\"",
        slug: "m18-fuel-klucz-udarowy-3-4",
        category: "klucze",
        description: "Klucz udarowy 3/4\" do najbardziej wymagających zastosowań przemysłowych.",
        originalPrice: "1899.00",
        exhibitionPrice: "1199.00",
        image: "",
        sku: "M18FHIWF34-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Moment: 1627 Nm", "Gniazdo 3/4\"", "4 tryby pracy", "Silnik POWERSTATE"],
      },
      {
        name: "M12 Klucz udarowy kompaktowy",
        slug: "m12-klucz-udarowy-kompaktowy",
        category: "klucze",
        description: "Kompaktowy klucz udarowy M12 do prac w ograniczonych przestrzeniach.",
        originalPrice: "599.00",
        exhibitionPrice: "379.00",
        image: "",
        sku: "M12CIW38-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Moment: 203 Nm", "Gniazdo 3/8\"", "Długość: 135mm", "Waga: 1.1kg"],
      },
      {
        name: "M18 Klucz dynamometryczny",
        slug: "m18-klucz-dynamometryczny",
        category: "klucze",
        description: "Precyzyjny klucz dynamometryczny z kontrolą momentu.",
        originalPrice: "1499.00",
        exhibitionPrice: "949.00",
        image: "",
        sku: "M18ONEFTR-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Zakres: 20-200 Nm", "ONE-KEY", "Dokładność ±2%", "4 tryby pracy"],
      },
      {
        name: "M18 FUEL Zakrętarka udarowa",
        slug: "m18-fuel-zakretarka-udarowa",
        category: "klucze",
        description: "Zakrętarka udarowa do szybkiej pracy z śrubami i wkrętami.",
        originalPrice: "899.00",
        exhibitionPrice: "569.00",
        image: "",
        sku: "M18FID2-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Moment: 271 Nm", "Gniazdo 1/4\"", "Tryb Precision Wrench", "Kompaktowa"],
      },
      {
        name: "M18 Klucz kątowy udarowy",
        slug: "m18-klucz-katowy-udarowy",
        category: "klucze",
        description: "Klucz kątowy udarowy do pracy w trudnodostępnych miejscach.",
        originalPrice: "1299.00",
        exhibitionPrice: "799.00",
        image: "",
        sku: "M18FRADH-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Głowica kątowa", "Moment: 250 Nm", "Gniazdo 1/2\"", "Kompaktowa konstrukcja"],
      },
      {
        name: "M12 FUEL Klucz zapadkowy",
        slug: "m12-fuel-klucz-zapadkowy",
        category: "klucze",
        description: "Elektryczny klucz zapadkowy M12 FUEL do precyzyjnej pracy.",
        originalPrice: "749.00",
        exhibitionPrice: "469.00",
        image: "",
        sku: "M12FIR38-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Gniazdo 3/8\"", "Moment: 61 Nm", "Głowica niskoprofilowa", "LED podświetlenie"],
      },
      {
        name: "M18 Klucz udarowy High Torque",
        slug: "m18-klucz-udarowy-high-torque",
        category: "klucze",
        description: "Klucz udarowy o najwyższym momencie obrotowym w ofercie Milwaukee.",
        originalPrice: "1799.00",
        exhibitionPrice: "1149.00",
        image: "",
        sku: "M18FHIWF12-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Moment: 2034 Nm", "Gniazdo 1/2\"", "Friction Ring", "Tryb Auto-Shut Off"],
      },
      {
        name: "M18 ONE-KEY Klucz udarowy",
        slug: "m18-one-key-klucz-udarowy",
        category: "klucze",
        description: "Klucz udarowy z technologią ONE-KEY dla profesjonalistów.",
        originalPrice: "1399.00",
        exhibitionPrice: "889.00",
        image: "",
        sku: "M18ONEFHIWF12-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["ONE-KEY", "Moment: 1492 Nm", "4 tryby", "Bluetooth"],
      },
      // Dodatkowe młoty
      {
        name: "M18 FUEL Młot wyburzeniowy",
        slug: "m18-fuel-mlot-wyburzeniowy",
        category: "mloty",
        description: "Potężny młot wyburzeniowy M18 FUEL do ciężkich prac rozbiórkowych.",
        originalPrice: "2499.00",
        exhibitionPrice: "1599.00",
        image: "",
        sku: "M18FHM-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Energia udaru: 8.1 J", "SDS-Max", "System AVS", "Silnik bezszczotkowy"],
      },
      {
        name: "M18 Młot kombinowany SDS-Max",
        slug: "m18-mlot-kombinowany-sds-max",
        category: "mloty",
        description: "Młot kombinowany z funkcją wiercenia i kucia.",
        originalPrice: "1999.00",
        exhibitionPrice: "1299.00",
        image: "",
        sku: "M18CHM-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["SDS-Max", "Energia: 5.7 J", "3 tryby pracy", "System ochrony AVS"],
      },
      {
        name: "M12 Młot udarowo-obrotowy kompaktowy",
        slug: "m12-mlot-udarowo-obrotowy-kompaktowy",
        category: "mloty",
        description: "Kompaktowy młot M12 SDS-Plus do codziennych zastosowań.",
        originalPrice: "649.00",
        exhibitionPrice: "399.00",
        image: "",
        sku: "M12H-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["SDS-Plus", "Energia: 1.0 J", "Długość: 310mm", "Waga: 2.0kg"],
      },
      {
        name: "M18 FUEL Młot pneumatyczny",
        slug: "m18-fuel-mlot-pneumatyczny",
        category: "mloty",
        description: "Młot pneumatyczny do precyzyjnych prac kucia i obróbki.",
        originalPrice: "1799.00",
        exhibitionPrice: "1149.00",
        image: "",
        sku: "M18FHP-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Udar 1900/min", "Energia: 2.5 J", "Szybkozłącze chwyt", "System AVS"],
      },
      {
        name: "M18 Młotek udarowy",
        slug: "m18-mlotek-udarowy",
        category: "mloty",
        description: "Kompaktowy młotek udarowy SDS-Plus do wiercenia i kucia.",
        originalPrice: "799.00",
        exhibitionPrice: "499.00",
        image: "",
        sku: "M18BH-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["SDS-Plus", "Energia: 1.9 J", "3 tryby pracy", "Uchwyt antywibracyjny"],
      },
      {
        name: "M18 FUEL Młot burzący SDS-Max",
        slug: "m18-fuel-mlot-burzacy-sds-max",
        category: "mloty",
        description: "Młot burzący o wyjątkowej sile udaru do profesjonalnych zastosowań.",
        originalPrice: "2799.00",
        exhibitionPrice: "1799.00",
        image: "",
        sku: "M18FHM-302C",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Energia: 11.9 J", "SDS-Max", "AVS", "ONE-KEY ready"],
      },
      {
        name: "M18 Młot obrotowy do rdzeni",
        slug: "m18-mlot-obrotowy-rdzeni",
        category: "mloty",
        description: "Specjalistyczny młot do wiercenia rdzeni diamentowych.",
        originalPrice: "1599.00",
        exhibitionPrice: "999.00",
        image: "",
        sku: "M18FDD-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Korony do 162mm", "System chłodzenia wodą", "2 prędkości", "Elektronika REDLINK"],
      },
      {
        name: "M12 Młot SDS-Plus mini",
        slug: "m12-mlot-sds-plus-mini",
        category: "mloty",
        description: "Ultra kompaktowy młot M12 do prac instalacyjnych.",
        originalPrice: "549.00",
        exhibitionPrice: "339.00",
        image: "",
        sku: "M12H-202C",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["SDS-Plus", "Energia: 0.9 J", "Waga: 1.7kg", "LED podświetlenie"],
      },
      {
        name: "M18 FUEL Młot wibracyjny",
        slug: "m18-fuel-mlot-wibracyjny",
        category: "mloty",
        description: "Młot wibracyjny do ubijania i zagęszczania gruntu.",
        originalPrice: "2299.00",
        exhibitionPrice: "1449.00",
        image: "",
        sku: "M18FVC-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Wibracje: 3600/min", "System AVS", "Siła udaru regulowana", "Rączka antywibracyjna"],
      },
      // Dodatkowe zestawy narzędzi
      {
        name: "Zestaw combo M18 FUEL 2 narzędzia",
        slug: "zestaw-combo-m18-fuel-2",
        category: "zestawy",
        description: "Zestaw M18 FUEL: wiertarko-wkrętarka + zakrętarka udarowa + 2 akumulatory + ładowarka.",
        originalPrice: "1799.00",
        exhibitionPrice: "1149.00",
        image: "",
        sku: "M18FPP2A2-502X",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["2 narzędzia M18 FUEL", "2x akumulator 5.0Ah", "Ładowarka M12-18FC", "Walizka HD Box"],
      },
      {
        name: "Zestaw combo M18 FUEL 3 narzędzia",
        slug: "zestaw-combo-m18-fuel-3",
        category: "zestawy",
        description: "Zestaw M18 FUEL: wiertarka + zakrętarka + szlifierka kątowa + akcesoria.",
        originalPrice: "2499.00",
        exhibitionPrice: "1599.00",
        image: "",
        sku: "M18FPP3A-503B",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["3 narzędzia M18 FUEL", "3x akumulator 5.0Ah", "Ładowarka szybka", "Walizka systemowa"],
      },
      {
        name: "Zestaw combo M12 FUEL 4 narzędzia",
        slug: "zestaw-combo-m12-fuel-4",
        category: "zestawy",
        description: "Kompletny zestaw M12 FUEL dla instalatorów i elektryków.",
        originalPrice: "2299.00",
        exhibitionPrice: "1449.00",
        image: "",
        sku: "M12FPP4A-402B",
        voltage: "12V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["4 narzędzia M12 FUEL", "2x akumulator 4.0Ah", "Ładowarka", "Torba narzędziowa"],
      },
      {
        name: "Zestaw combo M18 6 narzędzi budowlany",
        slug: "zestaw-combo-m18-6-budowlany",
        category: "zestawy",
        description: "Kompletny zestaw narzędzi budowlanych M18 dla profesjonalistów.",
        originalPrice: "4999.00",
        exhibitionPrice: "3199.00",
        image: "",
        sku: "M18FPP6E-503B",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["6 narzędzi M18 FUEL", "3x akumulator 5.0Ah", "Ładowarka podwójna", "Walizki systemowe"],
      },
      {
        name: "Zestaw startowy M18 bateria + ładowarka",
        slug: "zestaw-startowy-m18-bateria",
        category: "zestawy",
        description: "Zestaw startowy M18: akumulator 5.0Ah + ładowarka.",
        originalPrice: "599.00",
        exhibitionPrice: "399.00",
        image: "",
        sku: "M18NRG-501",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Akumulator M18 5.0Ah", "Ładowarka M12-18FC", "System REDLITHIUM"],
      },
      {
        name: "Zestaw akumulatorów M18 3-pak",
        slug: "zestaw-akumulatorow-m18-3pak",
        category: "zestawy",
        description: "Zestaw 3 akumulatorów M18 HIGH OUTPUT 6.0Ah.",
        originalPrice: "1299.00",
        exhibitionPrice: "849.00",
        image: "",
        sku: "M18HB6-3PK",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["3x akumulator 6.0Ah", "Technologia HIGH OUTPUT", "REDLITHIUM-ION"],
      },
      {
        name: "Zestaw combo M18/M12 uniwersalny",
        slug: "zestaw-combo-m18-m12-uniwersalny",
        category: "zestawy",
        description: "Uniwersalny zestaw łączący systemy M18 i M12.",
        originalPrice: "3299.00",
        exhibitionPrice: "2099.00",
        image: "",
        sku: "M1812FPP5A",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["3 narzędzia M18", "2 narzędzia M12", "Akumulatory obu systemów", "Ładowarka uniwersalna"],
      },
      {
        name: "Zestaw oświetleniowy M18 3 lampy",
        slug: "zestaw-oswietleniowy-m18-3-lampy",
        category: "zestawy",
        description: "Kompletny zestaw oświetlenia budowy M18.",
        originalPrice: "1599.00",
        exhibitionPrice: "999.00",
        image: "",
        sku: "M18LIGHT-3PK",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Lampa główna + reflektor + latarka", "Akumulatory 3.0Ah", "Ładowarka", "Torba"],
      },
      {
        name: "Zestaw combo M18 FUEL przemysłowy",
        slug: "zestaw-combo-m18-fuel-przemyslowy",
        category: "zestawy",
        description: "Profesjonalny zestaw M18 FUEL do zastosowań przemysłowych.",
        originalPrice: "6999.00",
        exhibitionPrice: "4499.00",
        image: "",
        sku: "M18FPP8A-603B",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["8 narzędzi FUEL", "6x akumulator 6.0Ah", "Ładowarka szybka podwójna", "Zestaw walizek"],
      },
      {
        name: "Zestaw combo M12 kompaktowy dla elektryka",
        slug: "zestaw-combo-m12-elektryka",
        category: "zestawy",
        description: "Specjalistyczny zestaw M12 dla elektryków i instalatorów.",
        originalPrice: "1999.00",
        exhibitionPrice: "1299.00",
        image: "",
        sku: "M12ELEC-5PK",
        voltage: "12V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["5 narzędzi specjalistycznych", "Akumulatory 2.0 + 4.0Ah", "Ładowarka", "Torba narzędziowa"],
      },
      // Piły
      {
        name: "M18 FUEL Piła szablasta",
        slug: "m18-fuel-pila-szablasta",
        category: "pily",
        description: "Wydajna piła szablasta M18 FUEL z systemem FIXTEC.",
        originalPrice: "899.00",
        exhibitionPrice: "569.00",
        image: "",
        sku: "M18FSX-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Skok: 32mm", "System FIXTEC", "Silnik bezszczotkowy", "LED podświetlenie"],
      },
      {
        name: "M18 FUEL Piła tarczowa 190mm",
        slug: "m18-fuel-pila-tarczowa-190mm",
        category: "pily",
        description: "Piła tarczowa 190mm do precyzyjnych cięć.",
        originalPrice: "799.00",
        exhibitionPrice: "499.00",
        image: "",
        sku: "M18FCS66-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza: 190mm", "Głębokość cięcia: 66mm", "Prowadnica laserowa", "Blokada wrzeciona"],
      },
      {
        name: "M12 FUEL Piła akumulatorowa HACKZALL",
        slug: "m12-fuel-pila-hackzall",
        category: "pily",
        description: "Kompaktowa piła szablasta M12 FUEL HACKZALL.",
        originalPrice: "649.00",
        exhibitionPrice: "399.00",
        image: "",
        sku: "M12CHZ-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Ultra kompaktowa", "Skok: 19mm", "Szybkomocowanie ostrza", "Waga: 1.4kg"],
      },
      {
        name: "M18 FUEL Piła taśmowa przenośna",
        slug: "m18-fuel-pila-tasmowa-przenośna",
        category: "pily",
        description: "Bezprzewodowa piła taśmowa do cięcia rur i profili.",
        originalPrice: "1599.00",
        exhibitionPrice: "999.00",
        image: "",
        sku: "M18CBS125-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Taśma 835mm", "Cięcie rur do 125mm", "System chłodzenia", "Elektronika REDLINK"],
      },
      {
        name: "M18 Piła posuwowa SAWZALL",
        slug: "m18-pila-posuwowa-sawzall",
        category: "pily",
        description: "Klasyczna piła SAWZALL do wymagających zastosowań.",
        originalPrice: "749.00",
        exhibitionPrice: "479.00",
        image: "",
        sku: "M18BSX-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Skok: 28mm", "Regulacja prędkości", "FIXTEC", "Uchwyt antywibracyjny"],
      },
      {
        name: "M18 FUEL Piła tarczowa 184mm z szyną",
        slug: "m18-fuel-pila-tarczowa-szyna",
        category: "pily",
        description: "Piła tarczowa z systemem prowadzenia szynowego.",
        originalPrice: "1299.00",
        exhibitionPrice: "829.00",
        image: "",
        sku: "M18FTS210-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza: 184mm", "Szyna prowadząca", "Głębokość: 57mm", "System odpylania"],
      },
      {
        name: "M12 Piła tarczowa 140mm",
        slug: "m12-pila-tarczowa-140mm",
        category: "pily",
        description: "Kompaktowa piła tarczowa M12 do prac wykończeniowych.",
        originalPrice: "549.00",
        exhibitionPrice: "339.00",
        image: "",
        sku: "M12CCS44-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza: 140mm", "Głębokość: 44mm", "LED", "Kompaktowa konstrukcja"],
      },
      {
        name: "M18 FUEL Piła do metalu",
        slug: "m18-fuel-pila-metalu",
        category: "pily",
        description: "Specjalistyczna piła do cięcia metalu z chłodzeniem.",
        originalPrice: "1199.00",
        exhibitionPrice: "759.00",
        image: "",
        sku: "M18FMCS-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza: 203mm", "System chłodzenia", "Cięcie na sucho", "Iskry minimalne"],
      },
      {
        name: "M18 Piła łańcuchowa 300mm",
        slug: "m18-pila-lancuchowa-300mm",
        category: "pily",
        description: "Piła łańcuchowa M18 do cięcia drewna.",
        originalPrice: "899.00",
        exhibitionPrice: "569.00",
        image: "",
        sku: "M18FCHS-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Długość prowadnicy: 300mm", "Napinanie bez narzędzi", "Automatyczne smarowanie", "Hamulec łańcucha"],
      },
      {
        name: "M18 FUEL Piła stołowa jednostronna",
        slug: "m18-fuel-pila-stolowa",
        category: "pily",
        description: "Mobilna piła stołowa do cięć poprzecznych.",
        originalPrice: "2299.00",
        exhibitionPrice: "1449.00",
        image: "",
        sku: "M18FMS254-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Tarcza: 254mm", "Kąt cięcia: 50°", "Laser prowadzący", "Stół roboczy składany"],
      },
      // Oświetlenie
      {
        name: "M18 Lampa obszarowa LED ROVER",
        slug: "m18-lampa-obszarowa-rover",
        category: "oswietlenie",
        description: "Wydajna lampa obszarowa M18 ROVER z montażem na statywie.",
        originalPrice: "699.00",
        exhibitionPrice: "449.00",
        image: "",
        sku: "M18ONERSLSP-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["4400 lumenów", "Montaż na statywie", "Obrotowa głowica", "Czas pracy: 8h"],
      },
      {
        name: "M12 Latarka TILT LED",
        slug: "m12-latarka-tilt-led",
        category: "oswietlenie",
        description: "Kompaktowa latarka M12 z regulowaną głowicą.",
        originalPrice: "199.00",
        exhibitionPrice: "129.00",
        image: "",
        sku: "M12TLED-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["220 lumenów", "Głowica obrotowa 90°", "Magnes mocujący", "Hak zawieszenia"],
      },
      {
        name: "M18 Reflektor budowlany LED",
        slug: "m18-reflektor-budowlany",
        category: "oswietlenie",
        description: "Wydajny reflektor LED do oświetlenia budów i warsztatów.",
        originalPrice: "599.00",
        exhibitionPrice: "379.00",
        image: "",
        sku: "M18HAL-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["3000 lumenów", "Statyw regulowany", "Odporność IP54", "Kąt świecenia 120°"],
      },
      {
        name: "M12 Lampa inspekcyjna wężowa LED",
        slug: "m12-lampa-inspekcyjna-wezowa",
        category: "oswietlenie",
        description: "Elastyczna lampa wężowa do trudnodostępnych miejsc.",
        originalPrice: "349.00",
        exhibitionPrice: "229.00",
        image: "",
        sku: "M12IL-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Elastyczny wąż 280mm", "LED w głowicy", "Magnes", "Hak zawieszenia"],
      },
      {
        name: "M18 Lampa podłogowa RADIUS LED",
        slug: "m18-lampa-podlogowa-radius",
        category: "oswietlenie",
        description: "Lampa podłogowa LED z montażem wszechstronnym.",
        originalPrice: "899.00",
        exhibitionPrice: "579.00",
        image: "",
        sku: "M18ONERSAL-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["4400 lumenów", "Montaż wielopozycyjny", "Statyw składany", "IP54"],
      },
      {
        name: "M12 Latarka czołowa HL LED",
        slug: "m12-latarka-czolowa-hl",
        category: "oswietlenie",
        description: "Latarka czołowa LED zasilana akumulatorem M12.",
        originalPrice: "299.00",
        exhibitionPrice: "189.00",
        image: "",
        sku: "M12HL-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["475 lumenów", "Czas pracy: 10h", "3 tryby świecenia", "Pas regulowany"],
      },
      {
        name: "M18 Lampa warsztatowa montażowa",
        slug: "m18-lampa-warsztatowa-montazowa",
        category: "oswietlenie",
        description: "Lampa montażowa LED do pracy w warsztacie.",
        originalPrice: "449.00",
        exhibitionPrice: "289.00",
        image: "",
        sku: "M18UBL-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["1400 lumenów", "Uchwyt magnetyczny", "Hak zawieszenia", "Obrotowa głowica"],
      },
      {
        name: "M12 Latarka akumulatorowa REDLITHIUM",
        slug: "m12-latarka-redlithium",
        category: "oswietlenie",
        description: "Kompaktowa latarka LED M12 REDLITHIUM.",
        originalPrice: "179.00",
        exhibitionPrice: "119.00",
        image: "",
        sku: "M12SLED-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["135 lumenów", "Klips do paska", "LED trwałość 50000h", "Wytrzymała obudowa"],
      },
      {
        name: "M18 System oświetlenia ONE-KEY",
        slug: "m18-oswietlenie-one-key",
        category: "oswietlenie",
        description: "Inteligentny system oświetlenia z kontrolą ONE-KEY.",
        originalPrice: "1299.00",
        exhibitionPrice: "849.00",
        image: "",
        sku: "M18ONESLSP-0",
        voltage: "18V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["5600 lumenów", "Kontrola Bluetooth ONE-KEY", "Statyw teleskopowy", "4 tryby pracy"],
      },
      {
        name: "M12 Lampa liniowa LED STICK",
        slug: "m12-lampa-liniowa-stick",
        category: "oswietlenie",
        description: "Liniowa lampa LED w formacie stick.",
        originalPrice: "249.00",
        exhibitionPrice: "159.00",
        image: "",
        sku: "M12SL-0",
        voltage: "12V",
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["220 lumenów", "Magnes neodymowy", "Hak mocujący", "3 tryby jasności"],
      },
      // Akcesoria
      {
        name: "Zestaw wierteł HSS-G Milwaukee 19szt",
        slug: "zestaw-wiertel-hss-g-19szt",
        category: "akcesoria",
        description: "Profesjonalny zestaw wierteł HSS-G w metalowej kasecie.",
        originalPrice: "199.00",
        exhibitionPrice: "129.00",
        image: "",
        sku: "4932352374",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["19 wierteł 1-10mm", "HSS-G", "Kaseta metalowa", "Szlifowane precyzyjnie"],
      },
      {
        name: "Zestaw bitów SHOCKWAVE 56szt",
        slug: "zestaw-bitow-shockwave-56szt",
        category: "akcesoria",
        description: "Kompletny zestaw bitów udarowych SHOCKWAVE.",
        originalPrice: "349.00",
        exhibitionPrice: "229.00",
        image: "",
        sku: "4932430904",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["56 elementów", "Technologia SHOCKWAVE", "Futerał modułowy", "Bity udarowe"],
      },
      {
        name: "Walizka systemowa PACKOUT",
        slug: "walizka-systemowa-packout",
        category: "akcesoria",
        description: "Duża walizka systemowa PACKOUT z organizerami.",
        originalPrice: "599.00",
        exhibitionPrice: "379.00",
        image: "",
        sku: "4932464078",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["System stackowania", "Wytrzymały", "Organizery wewnętrzne", "Zamki metalowe"],
      },
      {
        name: "Torba narzędziowa 600mm",
        slug: "torba-narzędziowa-600mm",
        category: "akcesoria",
        description: "Pojemna torba narzędziowa z wieloma kieszeniami.",
        originalPrice: "299.00",
        exhibitionPrice: "189.00",
        image: "",
        sku: "4932464085",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Długość: 600mm", "Materiał 1680D", "40 kieszeni", "Wzmocnione dno"],
      },
      {
        name: "Zestaw kluczy nasadowych 1/2\" 56szt",
        slug: "zestaw-kluczy-nasadowych-56szt",
        category: "akcesoria",
        description: "Kompletny zestaw kluczy nasadowych 1/2\".",
        originalPrice: "899.00",
        exhibitionPrice: "579.00",
        image: "",
        sku: "4932464945",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["56 elementów", "Gniazdo 1/2\"", "Stal CrV", "Walizka metalowa"],
      },
      {
        name: "Wiertła SDS-Plus SHOCKWAVE 7szt",
        slug: "wiertla-sds-plus-shockwave-7szt",
        category: "akcesoria",
        description: "Zestaw wierteł SDS-Plus do betonu.",
        originalPrice: "249.00",
        exhibitionPrice: "159.00",
        image: "",
        sku: "4932471085",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["7 wierteł 5-12mm", "SDS-Plus", "Głowica z węglików", "4-ostrze"],
      },
      {
        name: "Organizer PACKOUT niski",
        slug: "organizer-packout-niski",
        category: "akcesoria",
        description: "Kompaktowy organizer PACKOUT do drobnych elementów.",
        originalPrice: "199.00",
        exhibitionPrice: "129.00",
        image: "",
        sku: "4932464082",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["10 przegródek", "System PACKOUT", "Przezroczysta pokrywa", "Kompaktowy"],
      },
      {
        name: "Pas monterski regulowany",
        slug: "pas-monterski-regulowany",
        category: "akcesoria",
        description: "Profesjonalny pas monterski z kieszeniami.",
        originalPrice: "399.00",
        exhibitionPrice: "259.00",
        image: "",
        sku: "4932464084",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Regulowany rozmiar", "Wytrzymały materiał", "Kieszenie na narzędzia", "Uchwyty na młotek"],
      },
      {
        name: "Tarcze diamentowe turbo 125mm 5szt",
        slug: "tarcze-diamentowe-turbo-125mm-5szt",
        category: "akcesoria",
        description: "Zestaw tarcz diamentowych turbo do betonu.",
        originalPrice: "299.00",
        exhibitionPrice: "189.00",
        image: "",
        sku: "4932399527",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["5 tarcz 125mm", "Segment turbo", "Do betonu i kamienia", "Otwór 22.2mm"],
      },
      {
        name: "Zestaw pił SAWZALL 15szt",
        slug: "zestaw-pil-sawzall-15szt",
        category: "akcesoria",
        description: "Kompletny zestaw ostrzy do pił szablastych.",
        originalPrice: "199.00",
        exhibitionPrice: "129.00",
        image: "",
        sku: "4932430941",
        voltage: null,
        batteryIncluded: false,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["15 ostrzy", "Do drewna i metalu", "Różne długości", "Kaseta z organizacją"],
      },
      // Zestawy specjalistyczne
      {
        name: "Zestaw hydraulika M18 specjalistyczny",
        slug: "zestaw-hydraulika-m18",
        category: "zestawy-specjalistyczne",
        description: "Kompletny zestaw narzędzi dla hydraulików M18.",
        originalPrice: "3999.00",
        exhibitionPrice: "2599.00",
        image: "",
        sku: "M18PLUMB-SET",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Prasa do rur", "Wiertarka kątowa", "Latarka", "3x akumulator 5.0Ah", "Ładowarka", "Walizki PACKOUT"],
      },
      {
        name: "Zestaw montera HVAC M18 FUEL",
        slug: "zestaw-montera-hvac-m18",
        category: "zestawy-specjalistyczne",
        description: "Profesjonalny zestaw dla monterów wentylacji i klimatyzacji.",
        originalPrice: "4499.00",
        exhibitionPrice: "2899.00",
        image: "",
        sku: "M18HVAC-SET",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Nożyce do blachy", "Wiertarka", "Zakrętarka", "Szlifierka", "4x akumulator", "System PACKOUT"],
      },
      {
        name: "Zestaw elektryka instalacyjny M12",
        slug: "zestaw-elektryka-instalacyjny-m12",
        category: "zestawy-specjalistyczne",
        description: "Kompaktowy zestaw M12 dla elektryków instalacyjnych.",
        originalPrice: "2799.00",
        exhibitionPrice: "1799.00",
        image: "",
        sku: "M12ELEC-INST",
        voltage: "12V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Wiertarka", "Zakrętarka", "Multitool", "Latarka", "Miernik", "Torba specjalistyczna"],
      },
      {
        name: "Zestaw cieśli budowlanej M18 PRO",
        slug: "zestaw-ciesli-budowlanej-m18",
        category: "zestawy-specjalistyczne",
        description: "Zestaw profesjonalny dla cieśli i stolarzy budowlanych.",
        originalPrice: "5999.00",
        exhibitionPrice: "3899.00",
        image: "",
        sku: "M18CARP-PRO",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Piła tarczowa", "Piła szablasta", "Wiertarka", "Zakrętarka", "Szlifierka", "6x akumulator"],
      },
      {
        name: "Zestaw dekarza M18 specjalny",
        slug: "zestaw-dekarza-m18",
        category: "zestawy-specjalistyczne",
        description: "Specjalistyczny zestaw dla dekarzy i blacharzy.",
        originalPrice: "3499.00",
        exhibitionPrice: "2299.00",
        image: "",
        sku: "M18ROOF-SET",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Nożyce do blachy", "Zakrętarka udarowa", "Wiertarka", "Nożyce prostopadłe", "Akcesoria specjalistyczne"],
      },
      {
        name: "Zestaw mechanika samochodowego M18",
        slug: "zestaw-mechanika-samochodowego-m18",
        category: "zestawy-specjalistyczne",
        description: "Kompletny zestaw dla mechaników samochodowych.",
        originalPrice: "4999.00",
        exhibitionPrice: "3199.00",
        image: "",
        sku: "M18AUTO-MECH",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Klucz udarowy 1/2\"", "Zakrętarka", "Szlifierka", "Lampa obszarowa", "Wózek narzędziowy"],
      },
      {
        name: "Zestaw spawacza M18 kompletny",
        slug: "zestaw-spawacza-m18",
        category: "zestawy-specjalistyczne",
        description: "Profesjonalny zestaw dla spawaczy i ślusarzy.",
        originalPrice: "3299.00",
        exhibitionPrice: "2099.00",
        image: "",
        sku: "M18WELD-SET",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Szlifierka 125mm", "Szlifierka 180mm", "Latarka", "Okulary ochronne", "Akcesoria spawalnicze"],
      },
      {
        name: "Zestaw monterski przemysłowy M18",
        slug: "zestaw-monterski-przemyslowy-m18",
        category: "zestawy-specjalistyczne",
        description: "Zestaw dla monterów przemysłowych i serwisantów.",
        originalPrice: "6499.00",
        exhibitionPrice: "4199.00",
        image: "",
        sku: "M18IND-MAINT",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Klucz udarowy", "Wiertarka", "Szlifierka", "Multitool", "Latarka", "Kamera inspekcyjna", "Walizki PACKOUT"],
      },
      {
        name: "Zestaw stolarza meblowego M18 PRO",
        slug: "zestaw-stolarza-meblowego-m18",
        category: "zestawy-specjalistyczne",
        description: "Profesjonalny zestaw dla stolarzy meblowych.",
        originalPrice: "5499.00",
        exhibitionPrice: "3599.00",
        image: "",
        sku: "M18FURN-PRO",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Piła tarczowa", "Wyrzynarka", "Frezarka", "Szlifierka oscylacyjna", "Wiertarka", "System przechowywania"],
      },
      {
        name: "Zestaw instalatora gazu M18 certyfikowany",
        slug: "zestaw-instalatora-gazu-m18",
        category: "zestawy-specjalistyczne",
        description: "Certyfikowany zestaw dla instalatorów gazowych.",
        originalPrice: "3799.00",
        exhibitionPrice: "2499.00",
        image: "",
        sku: "M18GAS-INST",
        voltage: "18V",
        batteryIncluded: true,
        inStock: true,
        condition: "Bardzo dobry - produkt powystawowy",
        warranty: "gwarancja 12 miesięcy",
        features: ["Prasa do rur", "Wiertarka", "Zakrętarka", "Detektor gazu", "Latarka ATEX", "Narzędzia specjalistyczne"],
      },
    ];

    productsData.forEach((productData) => {
      const id = randomUUID();
      const product: Product = { ...productData, id };
      this.products.set(id, product);
    });
  }

  // Products
  async getAllProducts(): Promise<Product[]> {
    return Array.from(this.products.values());
  }

  async getProductById(id: string): Promise<Product | undefined> {
    return this.products.get(id);
  }

  async getProductBySlug(slug: string): Promise<Product | undefined> {
    return Array.from(this.products.values()).find((p) => p.slug === slug);
  }

  async getProductsByCategory(category: string): Promise<Product[]> {
    return Array.from(this.products.values()).filter((p) => p.category === category);
  }

  async createProduct(insertProduct: InsertProduct): Promise<Product> {
    const id = randomUUID();
    const product: Product = { 
      ...insertProduct, 
      id,
      voltage: insertProduct.voltage ?? null,
      batteryIncluded: insertProduct.batteryIncluded ?? false,
      inStock: insertProduct.inStock ?? true,
      condition: insertProduct.condition ?? "Bardzo dobry - produkt powystawowy",
      warranty: insertProduct.warranty ?? "gwarancja 12 miesięcy",
    };
    this.products.set(id, product);
    return product;
  }

  // Cart
  async getCartItems(sessionId: string): Promise<CartItemWithProduct[]> {
    const items = Array.from(this.cartItems.values()).filter(
      (item) => item.sessionId === sessionId
    );

    const itemsWithProducts: CartItemWithProduct[] = [];
    for (const item of items) {
      const product = await this.getProductById(item.productId);
      if (product) {
        itemsWithProducts.push({ ...item, product });
      }
    }
    return itemsWithProducts;
  }

  async addToCart(insertItem: InsertCartItem): Promise<CartItem> {
    // Check if item already exists
    const existing = Array.from(this.cartItems.values()).find(
      (item) =>
        item.sessionId === insertItem.sessionId && item.productId === insertItem.productId
    );

    if (existing) {
      // Update quantity
      existing.quantity += (insertItem.quantity || 1);
      this.cartItems.set(existing.id, existing);
      return existing;
    }

    // Create new item
    const id = randomUUID();
    const cartItem: CartItem = { 
      ...insertItem, 
      id,
      quantity: insertItem.quantity || 1
    };
    this.cartItems.set(id, cartItem);
    return cartItem;
  }

  async updateCartItemQuantity(id: string, quantity: number): Promise<CartItem | undefined> {
    const item = this.cartItems.get(id);
    if (!item) return undefined;

    item.quantity = quantity;
    this.cartItems.set(id, item);
    return item;
  }

  async removeFromCart(id: string): Promise<boolean> {
    return this.cartItems.delete(id);
  }
}

export const storage = new MemStorage();
